development:
  adapter: postgresql
  database: ads_microservice_development
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: ads_microservice_production
  pool: 5
  timeout: 5000
