development:
  adapter: postgresql
  database: ads_microservice_development

test:
  adapter: postgresql
  database: ads_microservice_test

production:
  adapter: postgresql
  database: ads_microservice_production
